### ISSUE TITLE
CERT_DATE_INVALID when clicking `Get questions` button

### ISSUE THREAD

**Issue by Jamelle-Boose** [humanloop/memorai#14]
**Describe the bug**
Nothing happens when clicking the `Get questions` button.

**To Reproduce**
1. Add this chrome extension to your browser 
2. Go to https://apps.ankiweb.net/ and download Anki for your desktop
3. Install the add-on
4. Try to generate questions from webpage
5. See an error

**Screenshots/Logs**
![image](https://user-images.githubusercontent.com/19831942/98897606-a80fcc00-2460-11eb-982e-d1cf9f51f762.png)

**Device**
 - Device: PC
 - OS: Windows 10
 - Browser: Chrome
 - Version: 86.0.4240.198 (Official Build) (64-bit)

**Comment by Jamelle-Boose** [comment]
@jordn any ideas?

**Comment by Jamelle-Boose** [comment]
![image](https://user-images.githubusercontent.com/19831942/98969487-bcd17b80-24c3-11eb-962d-500a3698af6a.png)

**Comment by jordn** [comment]
@Jamelle-Boose many thanks for opening this issue! Frankly, the team have let this extension deteriorate while we focused on our main app (humanloop.com ... live on product hunt today 👀 https://www.producthunt.com/posts/humanloop) 

Delighted to see real demand for us to fix it up. We'll commit to getting this working properly this weekend and rolled the Humanloop platform so it will get better with time too.

**Comment by Jamelle-Boose** [comment]
> @Jamelle-Boose many thanks for opening this issue! Frankly, the team have let this extension deteriorate while we focused on our main app (humanloop.com ... live on product hunt today 👀 https://www.producthunt.com/posts/humanloop)
> 
> Delighted to see real demand for us to fix it up. We'll commit to getting this working properly this weekend and rolled the Humanloop platform so it will get better with time too.

Thank you for the update. I was actually able to get it working by allowing the insecure site. Not ideal, but it worked.

**Comment by jordn** [comment]
Updated in the chrome store and github to use the new model endpoint. new extension should be live in ~5 days when chrome store gets round to reviewing these things. 

Glad to hear you're using it!
